baseURL = "https://people.inf.ethz.ch/amaximov/"
relativeURLs = false
canonifyURLs = true
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = true
title = 'Alexandra Maximova'
theme = 'huguette'
[params]
  css = true
[languages]
  [languages.en]
    languageName = "English"
    languageCode = 'en-US'
    disabled = false
    weight = 1
    contentDir = "content/en"
  [languages.de]
    languageName = "Deutsch"
  languageCode = 'de-CH'
    disabled = false
    weight = 2
    contentDir = "content/de"
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true